auto: true
permalink: /:title.html

# note the formatting here needs care:
# tab, hyphen, braces
# inside the braces, NB
#   - the space between the key and the value
#   - the comme after the folder
#   - the inverted commas around the name value
#
# for example:
#
#    - {folder: example_artist, name: "Example"}

allday:
    - {folder: beavis, name: "Amelia Beavis-Harrison"}
    - {folder: burn, name: "sean burn"}
    - {folder: liquid, name: "Liquid"}
    - {folder: smith, name: "Nicola Smith"}

12pm: 
    - {folder: cochrane, name: "Claire Cochrane"}
    - {folder: smallthings, name: "Small Things"}

1pm: 
    - {folder: aitchison, name: "Bill Aitchison"}
    - {folder: cochrane, name: "Claire Cochrane"}
    - {folder: jeeves, name: "Tim Jeeves"}    
    - {folder: radeva, name: "Katherina Radeva"}
    - {folder: smallthings, name: "Small Things"}
    
2pm: 
    - {folder: jeeves, name: "Tim Jeeves"} 
    - {folder: smallthings, name: "Small Things"}

3pm: 
    - {folder: jeeves, name: "Tim Jeeves"} 
    - {folder: smallthings, name: "Small Things"}

4pm: 
    - {folder: jeeves, name: "Tim Jeeves"} 


5pm: 
